### ISSUE TITLE
pkg_ressources removed in py 3.12

### ISSUE THREAD

**Issue by janesser** [lbovet/yglu#20]
https://docs.python.org/3/whatsnew/3.12.html

There is no more pkg_resources in python 3.12 (which is standard in e.g. ubuntu noble)

Longer situational description here: https://github.com/mu-editor/mu/issues/2485

Let's see if we can fix it.

```
> pipx run  yglu
Traceback (most recent call last):
  File "/home/jan/.local/pipx/.cache/3af48864adc97f2/bin/yglu", line 5, in <module>
    from yglu.cli import main
  File "/home/jan/.local/pipx/.cache/3af48864adc97f2/lib/python3.12/site-packages/yglu/cli.py", line 6, in <module>
    from .main import process
  File "/home/jan/.local/pipx/.cache/3af48864adc97f2/lib/python3.12/site-packages/yglu/main.py", line 5, in <module>
    from .builder import build_all
  File "/home/jan/.local/pipx/.cache/3af48864adc97f2/lib/python3.12/site-packages/yglu/builder.py", line 7, in <module>
    from .expression import Expression, Function, FunctionBlock
  File "/home/jan/.local/pipx/.cache/3af48864adc97f2/lib/python3.12/site-packages/yglu/expression.py", line 5, in <module>
    import yaql
  File "/home/jan/.local/pipx/.cache/3af48864adc97f2/lib/python3.12/site-packages/yaql/__init__.py", line 16, in <module>
    import pkg_resources
```

**Comment by janesser** [comment]
in fact its yagl.

**Comment by lbovet** [comment]
You can also install setuptools with `pip3 install setuptools`

**Comment by greyfairer** [comment]
@lbovet for me, it works, but it recently started showing ugly warnings with the latest version of setuptools:

/root/.local/share/pipx/venvs/yglu/lib/python3.12/site-packages/yaql/__init__.py:16: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

I see that YAQL itself has fixed it by switching to PBR in https://github.com/openstack/yaql/commit/bacaa7077d3c14519cdd28e0bb51373a3d352c9c, but it's released as 3.1.0, and yglu specifies yaql>=1.1.3,<3.0.

I think you can upgrade to yaql<4.0. They did remove the format function, but AFAICS, you only use YAQL to evaluate expressions, not for formatting.

My current workaround:

> RUN pip install yglu
> RUN pip install --upgrade --no-deps "yaql>=3.0,<4.0"

**Comment by mtnpke** [comment]
It is possible to use yglu==1.1.1 because it does not have the <3.0 constraint on yaql.
